### ISSUE TITLE
YAML syntax errors Homepage v0.9.11, particularly with bookmarks.yaml

### ISSUE THREAD

**Issue by BryanPoulin** [epoch-philosophy/homepage-example#1]
YAML syntax errors Homepage v0.9.11, particularly with `bookmarks.yaml`

```
...
...

- Access:
    - Hompage:
        icon: homepage.png
        href: https://gethomepage.dev/main/
        description: Homepage Documentation

...
...

```
![Screenshot 2024-11-11 at 8 22 53 AM (2)](https://github.com/user-attachments/assets/e32ecf19-bcea-42ea-8819-455f8da5c036)

Here’s the corrected YAML:

```
...
...

- Access:
    - Homepage:
        - icon: homepage.png
          href: https://gethomepage.dev/main/
          description: Documentation

...
...
```

**Comment by epoch-philosophy** [comment]
Oh, wow. Wonderful catch. Thank you for sharing this.

I use this primarily on Kubernetes and configure it via the configmap example. Wanted to leave some examples for docker specifically, but looks like that went totally past me. Updated it and fixed.

Thanks again for letting me know.
